---
kind: pipeline
type: docker
name: virtualenv-3.9-pipeline

steps:
  - name: lint
    image: registry.fluves.net/drone/cfactor/venv-3.9
    failure: ignore
    commands:
      - SKIP=no-commit-to-branch tox -e pre-commit

  - name: unit-tests
    image: registry.fluves.net/drone/cfactor/venv-3.9
    commands:
      - tox

  - name: build docs
    image: registry.fluves.net/drone/cfactor/venv-3.9
    commands:
      - git fetch origin --tags
      - pip install tox setuptools_scm
      - tox -e docs

  - name: build release
    image: registry.fluves.net/drone/cfactor/venv-3.9
    commands:
      - tox -e build

  - name: rsync-docs
    image: drillster/drone-rsync
    settings:
      hosts:
        - 10.28.0.24
      user: docs
      key:
        from_secret: rsync_key
      source: docs/_build/html/
      recursive: true
      target: /appdata/static/docs/cfactor
      secrets: [rsync_key]
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: report unit test coverage
    image: registry.fluves.net/drone/cfactor/venv-3.9
    commands:
      - "coverage3 report -m"
      - "coverage3 html"
      - coverage-badge >htmlcov/coverage.svg

  - name: upload test coverage
    image: drillster/drone-rsync
    settings:
      hosts:
        - 10.28.0.24
      user: docs
      key:
        from_secret: rsync_key
      source: htmlcov/*
      recursive: true
      target: /appdata/static/coverage/${DRONE_REPO_NAME}
      secrets: [rsync_key]
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

---
kind: pipeline
type: docker
name: build & release package
environment:
  GIT_LFS_SKIP_SMUDGE: "1"
depends_on:
  - virtualenv-3.9-pipeline

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: build release
    image: registry.fluves.net/drone/cfactor/venv-3.9
    commands:
      - tox -e build

  - name: gitea release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: release_token
      base_url: https://git.fluves.net
      files: "dist/*tar.gz,dist/*whl"
      prerelease: true
      note: automatic build
      title: ${DRONE_TAG}
    when:
      event: [tag]

---
kind: pipeline
type: docker
name: conda-pipeline

environment:
  CONDA_ACTIVATE: /opt/conda/bin/activate

workspace:
  path: /src/cfactor

steps:
  - name: environment
    image: registry.fluves.net/drone/cfactor/conda
    commands:
      - conda env create -p ./env -f environment.yml
      - . $CONDA_ACTIVATE
      - conda activate /src/cfactor/env
      - pip install -e .[develop]

  - name: unit-tests
    image: registry.fluves.net/drone/cfactor/conda
    commands:
      - . $CONDA_ACTIVATE
      - conda activate /src/cfactor/env
      - python -m pytest

---
kind: pipeline
type: docker
name: check branch size difference
# https://git.fluves.net/fluves/infrastructure/src/branch/master/drone/size_tool
steps:
  - name: check size
    image: registry.fluves.net/drone/infrastructure/git-file-size-diff

---
kind: pipeline
type: docker
name: report docstring
steps:
  - name: docstring coverage
    image: registry.fluves.net/drone/cfactor/venv-3.9
    failure: ignore
    commands:
      - interrogate src -vv -I -M
