name: cfactor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pre-commit
  - tox
  ## Python data science stack
  # - numpy
  # - scipy
  # - pandas
  # - xarray
  # - tqdm
  # - click
  # - ipython
  ## Python visualisation
  # - matplotlib
  # - seaborn
  # - bokeh
  # - plotly
  - pip:
     - --extra-index-url https://repo.fluves.net/fluves
     - --extra-index-url https://repo.fluves.net/marlinks
     - -e .  # install git checkout of cfactor in editable mode
