name: cfactor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pre-commit
  - tox
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - numba
  - pip:
     - -e .  # install git checkout of cfactor in editable mode
