ARG PYTHON_VERSION=3.9
FROM python:${PYTHON_VERSION}-bullseye

RUN python3 -m pip install --upgrade pip && pip install pytest tox virtualenv sphinx flake8 interrogate coverage-badge
# add large requirements to have them pre-installed already
# RUN pip install pandas scipy
